apiVersion: v1
kind: Secret
metadata:
  name: bugtracker-secrets
  namespace: bugtracker
type: Opaque
data:
  DB_USERNAME: YnVndHJhY2tlcg==
  DB_PASSWORD: YnVndHJhY2tlcjEyMw==
  DB_URL: amRiYzpwb3N0Z3Jlc3FsOi8vYnVndHJhY2tlci1kYi5jZnFjMndhYWd2YW4uZXUtY2VudHJhbC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvYnVndHJhY2tlcg==
